Update Go client dependencies [sc-52555]
chartmogul/chartmogul-go pull request #66
Opened 2023-08-18 21:20 UTC by macharmi

2023-10-18 11:17 UTC, macharmi commented
@pkopac I am trying to upgrade golang.org/x/net to version 0.7.0 but install is not working for old go versions

```
mohamed@mohamed-cm ~/src/go/pkg/mod/github.com/chartmogul/chartmogul-go/chartmogul-go (medali.charmi/sc-52555/update-go-client-dependencies) $ gvm use go1.13
Now using version go1.13
$ go version
go version go1.13 linux/amd64
mohamed@mohamed-cm ~/src/go/pkg/mod/github.com/chartmogul/chartmogul-go/chartmogul-go (medali.charmi/sc-52555/update-go-client-dependencies) $ 
mohamed@mohamed-cm ~/src/go/pkg/mod/github.com/chartmogul/chartmogul-go/chartmogul-go (medali.charmi/sc-52555/update-go-client-dependencies) $ 
mohamed@mohamed-cm ~/src/go/pkg/mod/github.com/chartmogul/chartmogul-go/chartmogul-go (medali.charmi/sc-52555/update-go-client-dependencies) $ make
# Get dependencies, -t is required for <Go 1.11
go get -t ./... || echo "Some dependencies failed"
go: downloading github.com/golang/mock v1.4.3
go: downloading github.com/go-test/deep v1.0.8
go: downloading github.com/parnurzeal/gorequest v0.2.16
go: downloading github.com/dnaeon/go-vcr v1.0.1
go: downloading github.com/cenkalti/backoff/v3 v3.2.2
go: downloading github.com/pkg/errors v0.9.1
go: extracting github.com/go-test/deep v1.0.8
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting github.com/golang/mock v1.4.3
go: extracting github.com/dnaeon/go-vcr v1.0.1
go: extracting github.com/cenkalti/backoff/v3 v3.2.2
go: extracting github.com/pkg/errors v0.9.1
go: extracting github.com/parnurzeal/gorequest v0.2.16
go: downloading gopkg.in/yaml.v2 v2.2.4
go: extracting github.com/davecgh/go-spew v1.1.1
go: downloading golang.org/x/net v0.7.0
go: downloading moul.io/http2curl v1.0.0
go: extracting gopkg.in/yaml.v2 v2.2.4
go: extracting moul.io/http2curl v1.0.0
go: extracting golang.org/x/net v0.7.0
go: finding github.com/dnaeon/go-vcr v1.0.1
go: finding github.com/golang/mock v1.4.3
go: finding github.com/cenkalti/backoff/v3 v3.2.2
go: finding github.com/parnurzeal/gorequest v0.2.16
go: finding github.com/pkg/errors v0.9.1
go: finding gopkg.in/yaml.v2 v2.2.4
go: finding golang.org/x/net v0.7.0
go: finding moul.io/http2curl v1.0.0
/home/mohamed/.gvm/pkgsets/go1.13/global/pkg/mod/golang.org/x/net@v0.7.0/publicsuffix/table.go:5:8: malformed module path "embed": missing dot in first path element
Some dependencies failed
go test -v -timeout=10m ./...
/home/mohamed/.gvm/pkgsets/go1.13/global/pkg/mod/golang.org/x/net@v0.7.0/publicsuffix/table.go:5:8: malformed module path "embed": missing dot in first path element
make: *** [Makefile:15: test] Error 1

``` 

See https://github.com/chartmogul/chartmogul-go/security/dependabot/14

2023-10-24 12:05 UTC, pkopac commented
@macharmi in general the guideline should be EOL of the language for our SDKs. I'd like to support older versions if it's easy, but if we have a blocker, I'd say it's fine to drop the support for anything that is not supported anymore. And it seems currently only 1.20 & 1.21 are supported.

https://endoflife.date/go

2023-10-30 13:05 UTC, pkopac requested changes
Please drop support for old Golang versions

2025-03-18 07:02 UTC, geopet85 commented
@macharmi @pkopac any chance we can fix and resolve this PR?

2025-12-04 14:07 UTC, closed without merging